server:
  port: 8080

spring:
  application.name: resource-service-first

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:4040/auth/user
    client:
      grant-type: client_credentials

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
